- src/utils/formatters.ts
close #54 
인자로 받는 string은 ISO 형식의 시간입니다. api get으로 받는 형식 그대로 쓰시면 됩니다.
> #54 상대적 시간계산 유틸함수 추가

- src/components/ui/ButtonDefault.tsx
- DefaultButton 컴포넌트 cn 함수 추가
- defaultStyle에서 px값 수정
> fix: 공용 default button 컴포넌트 - 클래스 병합되도록 수정

- src/lib/api/axios.ts
#68 #70 작업
리프레시 토큰으로 액세스 토큰 갱신
소셜 로그인(미회원시 회원가입)
> 백엔드 Auth API 완료

- src/utils/convertToColorArray.ts
close #101 
다른데서도 쓰일줄 알고 만들었는데 상세에서만 쓰이네요😅
> feat: 아로마 배열을 키보드 컬러 배열로 매핑하는 유틸함수 구현(#101)

- next.config.ts
- src/app/globals.css
- src/components/ui/KeyboardThumbnail.tsx
- 테일윈드 동적으로 값이 적용 되지 않는 부분 수정
- global.css 중괄호 누락된 부분 수정
- 기존 props중 ratio에 값을 객체로 받던 형식에서 ratioClass로 이름을 변경하고 클래스 네임으로 받아 머지하도록 수정하였습니다.
> Fix: KeyboardThumbnail 컴포넌트 수정

- .github/workflows/dev_workflow.yml
> cicd 배포시 env적용

- .github/workflows/dev_workflow.yml
- Dockerfile
> CICD작업시 미리 env파일을 빌드전 생성

- Dockerfile
> cicd Docker image생성시 .env cpoy하지 않음

- src/lib/api/axios.ts
- #112 
```
const data = await dataApi.request<return될 데이터 타입, body로 보내야하는 데이터 타입>({
path: '/users/me',
method: 'GET',
body?: {},
headers?: {}
cache?: string
});
```
> feat: fetch API 요청시 만료된 액세스 토큰 재발급 후 재요청하는 함수 추가 #112

- .github/workflows/dev_workflow.yml
- src/app/(global)/page.tsx
> cicd 재배포 .env.local로 변경

- Dockerfile
> cicd .env.local을 Dockerfile에서 Import

- .github/workflows/dev_workflow.yml
- Dockerfile
> npm run dev으로 변경

- Dockerfile
> Dockerfile 수정. 빌드과정 생략

- src/components/feature/LoginForm.tsx
- src/components/feature/SignUpForm.tsx
- 로그인, 회원가입 입력값에 공백 입력될 경우 trim으로 제거 처리
- react-hook-form의 `setValueAs` 사용
> Refactor: 로그인, 회원가입 입력값 처리 방식 개선 (trim 추가)

- src/components/feature/myProfile/MyKeyboardArea.tsx
- src/components/feature/myProfile/MyKeyboardItem.tsx
- src/components/feature/myProfile/MyKeyboardList.tsx
- src/components/feature/myProfile/MyReviewArea.tsx
- src/components/feature/reviewForm/ReviewFormCheckboxItem.tsx
- src/components/ui/Dropdown/DdButtonItem.tsx
- src/components/ui/Dropdown/DropdownWithSelectButton/index.tsx
- src/utils/convertToTypeArray.ts
- #182 
- 상달님 `KeyboardForm` 에서 초기값을 전달했을 때 타입부분에 RED라고 찍히더라구요! 그래서 그 부분을 조금 수정을 했습니다. 한번 확인해주시면 감사하겠습니다 :)
> Feat: myprofile 키보드 수정 API 연동

- .github/workflows/dev_workflow.yml
> 경로를 로그로 응답

- Dockerfile
> 경로를 상위로 변경

- .github/workflows/dev_workflow.yml
- Dockerfile
> git repository경로로 변경

- .github/workflows/dev_workflow.yml
> .env.local파일 덮어 쓰기

- .github/workflows/dev_workflow.yml
> .env.local파일 덮어 쓰기 - 강제

- src/app/globals.css
- src/components/feature/InputField/PasswordInputField.tsx
> Style: InputField padding right 조정 (비밀번호 필드에만 padding right 추가)

- src/app/(global)/keyboards/[keyboardid]/page.tsx
- src/components/feature/keyboardDetails/RatingsInfo.tsx
- src/components/feature/keyboardDetails/ReviewCard.tsx
- src/components/feature/keyboardDetails/ReviewList.tsx
- src/components/feature/myProfile/MyReviewItem.tsx
- src/components/feature/reviewForm/ReviewForm.tsx
close #60 
api연동해서 리뷰 생성, 수정, 삭제까지 상세 페이지 모든 기능 구현 완료했습니다!
> 상세페이지 기능 구현 #60

- src/components/feature/Slider/SliderSection.tsx
> Fix: SliderSection 클라이언트 컴포넌트로 변경

- src/components/feature/keyboardDetails/RatingsInfo.tsx
- src/components/feature/keyboardDetails/ReviewCard.tsx
- src/components/feature/keyboardDetails/ReviewList.tsx
- src/components/feature/myProfile/MyKeyboardItem.tsx
- src/components/feature/myProfile/MyReviewArea.tsx
- src/components/feature/myProfile/MyReviewItem.tsx
- src/components/feature/reviewForm/ReviewForm.tsx
- 리뷰 등록/수정 모달에 키보드 아이콘에서 키보드 이미지로 수정
- 마이프로필 페이지에서 키보드 아이템 클릭시 키보드 상세 페이지로 이동되도록 수정
> Chore: 마이프로필 페이지 수정

- src/app/(global)/keyboards/page.tsx
> fix: 필터 적용시 모달이 닫히도록변경

- src/components/ui/Toast/index.tsx
- Toast 컴포넌트 index.tsx 파일 하나만 수정했습니다. 충돌 여지 없을 것 같아서 셀프머지할게요~
> Fix: 토스트 닫기 버튼 클릭 시 제거 + 애니메이션

- src/app/globals.css
- src/components/layout/Header.tsx
- src/components/ui/Toast/index.tsx
> Feat: 헤더 메뉴 추가 ('모든 키보드', 클릭 시 /keyboards로 이동)

- src/app/(global)/keyboards/[keyboardid]/page.tsx
> fix:상세페이지 진입시 이전 페이지의 스크롤을 초기화해서 화면 상단부터 시작하도록 변경

- src/app/(global)/keyboards/page.tsx
- src/app/(global)/layout.tsx
- src/components/feature/keyboardDetails/KeyboardMiniCard.tsx
> Hotfix: 빌드 에러 수정 (footer import order error)

- src/components/feature/keyboardDetails/KeyboardInfoCard.tsx
> chore: 이미지 임시 인코딩 코드 삭제

- src/components/feature/keyboardDetails/ReviewList.tsx
> fix: 리뷰 없을 때 돌아가기 버튼 추가

- src/components/feature/Keyboards/Filter/FilterContent.tsx
- src/components/ui/InfoGuide.tsx
- 아이폰에서 호버클릭 안되는 이슈 해결
- 불필요한 주석 제거
> Fix: 아이폰에서 호버클릭 안되는 이슈 해결

- src/components/feature/RequireAuth.tsx
- src/lib/api/apiClient.ts
> refactor: 리다이렉션 로직 관심사 분리
